// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/linked-list": {
    params: {};
  };
  "/binary-search-tree": {
    params: {};
  };
  "/stack": {
    params: {};
  };
  "/queue": {
    params: {};
  };
  "/graph": {
    params: {};
  };
  "/trie": {
    params: {};
  };
  "/hashset": {
    params: {};
  };
  "/hashtable": {
    params: {};
  };
  "/heapq": {
    params: {};
  };
  "/java": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/linked-list" | "/binary-search-tree" | "/stack" | "/queue" | "/graph" | "/trie" | "/hashset" | "/hashtable" | "/heapq" | "/java";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/linked-list.tsx": {
    id: "routes/linked-list";
    page: "/linked-list";
  };
  "routes/binary-search-tree.tsx": {
    id: "routes/binary-search-tree";
    page: "/binary-search-tree";
  };
  "routes/stack.tsx": {
    id: "routes/stack";
    page: "/stack";
  };
  "routes/queue.tsx": {
    id: "routes/queue";
    page: "/queue";
  };
  "routes/graph.tsx": {
    id: "routes/graph";
    page: "/graph";
  };
  "routes/trie.tsx": {
    id: "routes/trie";
    page: "/trie";
  };
  "routes/hashset.tsx": {
    id: "routes/hashset";
    page: "/hashset";
  };
  "routes/hashtable.tsx": {
    id: "routes/hashtable";
    page: "/hashtable";
  };
  "routes/heapq.tsx": {
    id: "routes/heapq";
    page: "/heapq";
  };
  "routes/java.tsx": {
    id: "routes/java";
    page: "/java";
  };
};